POST http://localhost:8080/
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "users.CreateUser",
  "id": "1",
  "params": [{
    "email": "jaroslav@gmail.com",
    "password": "jar",
    "name": "jar"
  }]
}

###
POST http://localhost:8080/
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "users.GetUserById",
  "id": "2",
  "params": [{
    "id": 50
  }]

}

###



POST http://localhost:8080/
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "users.FindUsersByEmail",
  "id": "3",
  "params": [{
    "email": "jo%"
  }]

}


